apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-managedenv-test-deployment
  namespace: gitops-service-e2e
spec:
  destination:
    environment: gitops-managedenvironment-dev
    namespace: gitops-service-e2e
  source:
    path: resources/test-data/sample-gitops-repository/environments/overlays/dev
    repoURL: https://github.com/redhat-appstudio/managed-gitops
  type: automated
status:
  health:
    status: Healthy
  reconciledState:
    destination:
      name: gitops-managedenvironment-dev
      namespace: gitops-service-e2e
    source:
      branch: ""
      path: resources/test-data/sample-gitops-repository/environments/overlays/dev
      repoURL: https://github.com/redhat-appstudio/managed-gitops
  resources:
    - kind: ConfigMap
      name: environment-config-map
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: route.openshift.io
      health:
        message: Route is healthy
        status: Healthy
      kind: Route
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: route.openshift.io
      health:
        message: Route is healthy
        status: Healthy
      kind: Route
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
  sync:
    status: Synced
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: gitops-service-argocd
spec:
  destination:
    namespace: gitops-service-e2e
  project: default
  source:
    path: resources/test-data/sample-gitops-repository/environments/overlays/dev
    repoURL: https://github.com/redhat-appstudio/managed-gitops
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
status:
  health:
    status: Healthy
  history:
    - id: 0
      source:
        path: resources/test-data/sample-gitops-repository/environments/overlays/dev
        repoURL: https://github.com/redhat-appstudio/managed-gitops
  operationState:
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        syncOptions:
          - PrunePropagationPolicy=background
    phase: Succeeded
    syncResult:
      source:
        path: resources/test-data/sample-gitops-repository/environments/overlays/dev
        repoURL: https://github.com/redhat-appstudio/managed-gitops
  resources:
    - kind: ConfigMap
      name: environment-config-map
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: route.openshift.io
      health:
        message: Route is healthy
        status: Healthy
      kind: Route
      name: component-a
      namespace: gitops-service-e2e
      status: Synced
      version: v1
    - group: route.openshift.io
      health:
        message: Route is healthy
        status: Healthy
      kind: Route
      name: component-b
      namespace: gitops-service-e2e
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    images:
      - quay.io/jgwest-redhat/sample-workload:latest
  sync:
    comparedTo:
      destination:
        namespace: gitops-service-e2e
      source:
        path: resources/test-data/sample-gitops-repository/environments/overlays/dev
        repoURL: https://github.com/redhat-appstudio/managed-gitops
    status: Synced
