apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl-sync-run-multiple-seq
  namespace: gitops-service-e2e
spec:
  source:
    repoURL: https://github.com/managed-gitops-test-data/deployment-presync-hook
    path: guestbook-without-hook
  type: manual
