apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl-invalid-resources
  namespace: gitops-service-e2e
spec:
  source:
    repoURL: https://github.com/managed-gitops-test-data/gitops-repositories
    path: invalid-repository
  type: automated
