apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-managedenv-test-deployment
  namespace: gitops-service-e2e
spec:
  source:
    repoURL: https://github.com/redhat-appstudio/managed-gitops
    path: resources/test-data/sample-gitops-repository/environments/overlays/dev
  destination:
    environment: gitops-managedenvironment-dev
    namespace: gitops-service-e2e
  type: automated
