apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl-sync-run-multiple-aao
  namespace: gitops-service-e2e
spec:
  source:
    path: guestbook-without-hook
    repoURL: https://github.com/managed-gitops-test-data/deployment-presync-hook
  type: manual
status:
  health:
    status: Missing
  reconciledState:
    destination:
      name: ""
      namespace: gitops-service-e2e
    source:
      branch: ""
      path: guestbook-without-hook
      repoURL: https://github.com/managed-gitops-test-data/deployment-presync-hook
  resources:
    - health:
        status: Missing
      kind: Service
      name: guestbook-ui
      namespace: gitops-service-e2e
      status: OutOfSync
      version: v1
    - group: apps
      health:
        status: Missing
      kind: Deployment
      name: guestbook-ui
      namespace: gitops-service-e2e
      status: OutOfSync
      version: v1
  sync:
    revision: d390b220553954a12a19b5133ad2313e6b60691e
    status: OutOfSync
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: gitops-service-argocd
spec:
  destination:
    name: in-cluster
    namespace: gitops-service-e2e
  project: default
  source:
    path: guestbook-without-hook
    repoURL: https://github.com/managed-gitops-test-data/deployment-presync-hook
status:
  health:
    status: Missing
  resources:
    - health:
        status: Missing
      kind: Service
      name: guestbook-ui
      namespace: gitops-service-e2e
      status: OutOfSync
      version: v1
    - group: apps
      health:
        status: Missing
      kind: Deployment
      name: guestbook-ui
      namespace: gitops-service-e2e
      status: OutOfSync
      version: v1
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        name: in-cluster
        namespace: gitops-service-e2e
      source:
        path: guestbook-without-hook
        repoURL: https://github.com/managed-gitops-test-data/deployment-presync-hook
    revision: d390b220553954a12a19b5133ad2313e6b60691e
    status: OutOfSync
