apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeploymentSyncRun
metadata:
  name: test-syncrun-multiple-aao-1
  namespace: gitops-service-e2e
spec:
  gitopsDeploymentName: gitops-depl-sync-run-multiple-aao
  revisionID: main
---
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeploymentSyncRun
metadata:
  name: test-syncrun-multiple-aao-2
  namespace: gitops-service-e2e
spec:
  gitopsDeploymentName: gitops-depl-sync-run-multiple-aao
  revisionID: replicas-2
---
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeploymentSyncRun
metadata:
  name: test-syncrun-multiple-aao-3
  namespace: gitops-service-e2e
spec:
  gitopsDeploymentName: gitops-depl-sync-run-multiple-aao
  revisionID: replicas-3
