apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeploymentSyncRun
metadata:
  name: test-syncrun-new-update-spec
  namespace: gitops-service-e2e
spec:
  gitopsDeploymentName: gitops-depl-sync-run-new-update-spec
  revisionID: main
