apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: ""
  configManagementPlugins: ""
  dex.config: ""
  ga.anonymizeusers: "false"
  ga.trackingid: ""
  help.chatText: ""
  help.chatUrl: ""
  kustomize.buildOptions: ""
  repositories: ""
  repository.credentials: ""
  resource.exclusions: ""
  resource.inclusions: |-
    - apiGroups:
      - ""
      kinds:
      - "PersistentVolumeClaim"
      - "PersistentVolume"
      - "Secret"
      - "ConfigMap"
      - "Pod"
      - "Endpoint"
      - "Service"
      - "ServiceAccounts"
      clusters:
      - "*"
    - apiGroups:
      - "apps"
      kinds:
      - "ReplicaSet"
      - "StatefulSet"
      - "DaemonSet"
      - "Deployment"
      clusters:
      - "*"
    - apiGroups:
      - "discovery.k8s.io"
      kinds:
      - "EndpointSlice"
      clusters:
      - "*"
    - apiGroups:
      - "networking.k8s.io"
      kinds:
      - "Ingress"
      - "IngressClass"
      clusters:
      - "*"
    - apiGroups:
      - "rbac.authorization.k8s.io"
      kinds:
      - "RoleBinding"
      - "Role"
      clusters:
      - "*"
    - apiGroups:
      - "route.openshift.io"
      kinds:
      - "Route"
      clusters:
      - "*"
    - apiGroups:
      - "triggers.tekton.dev"
      kinds:
      - "EventListener"
      - "TriggerTemplate"
      clusters:
      - "*"
    - apiGroups:
      - "pipelinesascode.tekton.dev"
      kinds:
      - "Repository"
      clusters:
      - "*"
    - apiGroups:
      - "not.real.com"
      kinds:
      - "*"
      clusters:
      - "*"
  statusbadge.enabled: "false"
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: gitops-service-argocd
